using Microsoft.Xna.Framework;
using SexyBiscuit.Engine.Core;
using SexyBiscuit.Engine.Gameplay;
using SexyBiscuit.Engine.Rendering;

namespace SexyBiscuit.Engine.Scene;

/// <summary>
/// Starter scenes built in code, so a new project opens on something you can see and
/// fly around rather than an empty void.
/// </summary>
/// <remarks>
/// Every shape here is generated by <see cref="PrimitiveMesh"/> and every light is a
/// component, so a starter scene needs no asset files at all. That matters for a first
/// run: the editor can open a lit, navigable level before the user has imported anything.
/// </remarks>
public static class SceneTemplates
{
    /// <summary>
    /// The default 3D level: a floor, a sky, a sun with a fill light, three shapes to
    /// select, a player start and a game mode.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Modelled on Unreal's Basic level, which exists to answer one question immediately —
    /// is my viewport working? Everything in it is there to make a rendering problem
    /// obvious: the floor shows shadows and perspective, the sphere shows smooth shading,
    /// the cube shows hard edges, and the coloured shapes show that materials bind.
    /// </para>
    /// <para>
    /// The game mode and player start mean Play works straight away rather than dropping
    /// you into an unpossessed scene.
    /// </para>
    /// </remarks>
    /// <param name="name">Scene name.</param>
    public static Core.Scene CreateDefault3D(string name = "Untitled")
    {
        var scene = new Core.Scene(name);

        // -- Sky ------------------------------------------------------------
        // No cubemap, so the gradient fallback draws. A horizon makes it obvious
        // which way is up before any geometry loads.
        var sky = new Actor("Sky");
        sky.AddComponent<Transform3D>();
        var skybox = sky.AddComponent<Skybox>();
        skybox.GradientTop    = new Color(58, 92, 168);
        skybox.GradientBottom = new Color(178, 198, 224);
        scene.AddActor(sky, "background");

        // -- Lighting ---------------------------------------------------------
        var sun = new Actor("Directional Light");
        var sunTransform = sun.AddComponent<Transform3D>();
        sunTransform.Position    = new Vector3(0f, 10f, 0f);
        sunTransform.EulerAngles = new Vector3(-50f, 35f, 0f);

        var sunLight = sun.AddComponent<Light3D>();
        sunLight.Type         = LightType.Directional;
        sunLight.Color        = new Color(255, 248, 232);
        sunLight.Intensity    = 1.1f;
        sunLight.CastsShadows = true;
        scene.AddActor(sun);

        // A dim light from the opposite side. Without it the unlit faces of every object
        // are flat ambient and the shapes read as silhouettes.
        var fill = new Actor("Fill Light");
        var fillTransform = fill.AddComponent<Transform3D>();
        fillTransform.EulerAngles = new Vector3(-20f, -140f, 0f);

        var fillLight = fill.AddComponent<Light3D>();
        fillLight.Type      = LightType.Directional;
        fillLight.Color     = new Color(150, 175, 215);
        fillLight.Intensity = 0.35f;
        scene.AddActor(fill);

        // -- Floor ------------------------------------------------------------
        var floor = new Actor("Floor") { Tag = "Ground" };
        var floorTransform = floor.AddComponent<Transform3D>();
        floorTransform.LocalScale = new Vector3(30f, 1f, 30f);

        var floorMesh = floor.AddComponent<MeshRenderer>();
        floorMesh.MeshType = MeshPrimitive.Plane;
        floorMesh.Materials.Add(new Material3D
        {
            AlbedoColor = new Color(118, 122, 130),
            Roughness   = 0.9f,
        });
        scene.AddActor(floor);

        // -- Something to look at ---------------------------------------------
        // Three shapes rather than one: hard edges, smooth shading and a curved
        // silhouette each fail differently when lighting or normals are wrong.
        AddShape(scene, "Cube",     MeshPrimitive.Cube,     new Vector3(0f, 0.5f, 0f),
                 new Color(214, 92, 76),  roughness: 0.5f);

        AddShape(scene, "Sphere",   MeshPrimitive.Sphere,   new Vector3(-2.2f, 0.5f, 0f),
                 new Color(90, 150, 214), roughness: 0.25f);

        AddShape(scene, "Cylinder", MeshPrimitive.Cylinder, new Vector3(2.2f, 0.5f, 0f),
                 new Color(214, 178, 90), roughness: 0.65f);

        // -- Gameplay ----------------------------------------------------------
        var start = new Actor("Player Start");
        var startTransform = start.AddComponent<Transform3D>();
        startTransform.Position    = new Vector3(0f, 0f, 6f);
        startTransform.EulerAngles = new Vector3(0f, 180f, 0f);
        start.AddComponent<PlayerStart>();
        scene.AddActor(start);

        scene.AddActor(new GameMode());

        return scene;
    }

    /// <summary>
    /// A minimal 2D scene: a camera and nothing else.
    /// </summary>
    public static Core.Scene CreateDefault2D(string name = "Untitled")
    {
        var scene = new Core.Scene(name);

        var camera = new Actor("Camera 2D");
        camera.AddComponent<Camera2D>();
        scene.AddActor(camera);

        return scene;
    }

    /// <summary>Adds one lit primitive at a position, with a coloured material.</summary>
    private static void AddShape(Core.Scene scene, string name, MeshPrimitive shape,
                                 Vector3 position, Color colour, float roughness)
    {
        var actor = new Actor(name);
        actor.AddComponent<Transform3D>().Position = position;

        var mesh = actor.AddComponent<MeshRenderer>();
        mesh.MeshType = shape;
        mesh.Materials.Add(new Material3D { AlbedoColor = colour, Roughness = roughness });

        scene.AddActor(actor);
    }
}
