using System.Diagnostics;

namespace SexyBiscuit.Engine.Scripting;

/// <summary>
/// Generates a TypeScript declaration file (<c>.d.ts</c>) that describes the
/// entire SexyBiscuit script API exposed by <see cref="ScriptBridge"/>.
///
/// Drop the generated file into your scripts workspace and point VS Code at it
/// via a <c>jsconfig.json</c> or <c>tsconfig.json</c> <c>typeRoots</c> entry
/// to get full IntelliSense, hover types, and parameter hints with zero build steps.
///
/// Usage:
/// <code>
///   // At engine startup (editor mode):
///   TypeScriptDefinitions.WriteToFile("Scripts/sb-engine.d.ts");
/// </code>
/// </summary>
public static class TypeScriptDefinitions
{
    // =========================================================================
    // Public API
    // =========================================================================

    /// <summary>
    /// Returns the complete <c>.d.ts</c> content as a string.
    /// The declarations cover every global and lifecycle function exposed by
    /// <see cref="ScriptBridge"/> and <see cref="ScriptComponent"/>.
    /// </summary>
    public static string Generate() => DtsContent;

    /// <summary>
    /// Writes the <c>.d.ts</c> content to <paramref name="outputPath"/>,
    /// creating any intermediate directories as needed.
    /// Overwrites any existing file at that path.
    /// </summary>
    /// <param name="outputPath">
    /// Destination file path, e.g. <c>"Scripts/sb-engine.d.ts"</c>.
    /// </param>
    public static void WriteToFile(string outputPath)
    {
        if (string.IsNullOrWhiteSpace(outputPath))
            throw new ArgumentException("outputPath must not be empty.", nameof(outputPath));

        try
        {
            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(outputPath, DtsContent, System.Text.Encoding.UTF8);
            System.Diagnostics.Debug.WriteLine($"[TypeScriptDefinitions] Written to: {outputPath}");
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"[TypeScriptDefinitions] Failed to write '{outputPath}': {ex.Message}");
            throw;
        }
    }

    // =========================================================================
    // Declaration content
    // =========================================================================

    // Stored as a verbatim string constant so there is no runtime I/O or
    // reflection cost.  Update this whenever ScriptBridge changes.
    private const string DtsContent =
        """
        // =============================================================================
        // SexyBiscuit Engine — Script API Declarations
        // Auto-generated by TypeScriptDefinitions.cs — do not hand-edit.
        // Place this file in your Scripts/ folder and reference it from jsconfig.json.
        // =============================================================================

        // ---------------------------------------------------------------------------
        // actor — the Actor that owns this script component
        // ---------------------------------------------------------------------------
        declare const actor: {
            /** Display name of the actor (editable). */
            name: string;
            /** Tag string used for collision filtering and scene queries. */
            tag: string;
            /** Whether this actor is active and updated each frame. */
            active: boolean;
            /** Remove this actor from the scene at the end of the current frame. */
            destroy(): void;
        };

        // ---------------------------------------------------------------------------
        // transform — the actor's Transform component
        // ---------------------------------------------------------------------------
        declare const transform: {
            /** World-space X position. */
            x: number;
            /** World-space Y position. */
            y: number;
            /** World-space rotation in radians. */
            rotation: number;
            /** World-space horizontal scale. */
            scaleX: number;
            /** World-space vertical scale. */
            scaleY: number;
            /**
             * Rotates the actor so it faces the point (x, y) in world space.
             * @param x Target world X.
             * @param y Target world Y.
             */
            lookAt(x: number, y: number): void;
            /**
             * Returns the Euclidean distance from this transform to another.
             * @param other A transform proxy object (e.g. from Scene.find().transform).
             */
            distanceTo(other: { x: number; y: number }): number;
        };

        // ---------------------------------------------------------------------------
        // Input — input query API
        // ---------------------------------------------------------------------------
        declare const Input: {
            /**
             * Returns true on the frame the named action transitions from inactive to active.
             * @param action Action name as defined in the ActionMap.
             */
            isPressed(action: string): boolean;
            /**
             * Returns true while the named action is continuously active.
             * @param action Action name as defined in the ActionMap.
             */
            isHeld(action: string): boolean;
            /**
             * Returns true on the frame the named action transitions from active to inactive.
             * @param action Action name as defined in the ActionMap.
             */
            isReleased(action: string): boolean;
            /**
             * Returns the axis value for the named action in the range -1..1.
             * @param action Action name as defined in the ActionMap.
             */
            getAxis(action: string): number;
            /** Current mouse cursor X position in screen pixels (read-only). */
            readonly mouseX: number;
            /** Current mouse cursor Y position in screen pixels (read-only). */
            readonly mouseY: number;
        };

        // ---------------------------------------------------------------------------
        // Audio — audio playback API
        // ---------------------------------------------------------------------------
        /** Opaque handle returned by Audio.play(). Pass it to Audio.stop() to halt playback. */
        declare interface AudioHandle {
            readonly id: number;
        }

        declare const Audio: {
            /**
             * Begins managed playback of the audio file at the given path.
             * @param path Path to an audio file (.wav / .ogg / .mp3).
             * @returns An opaque handle; pass to stop() to halt playback.
             */
            play(path: string): AudioHandle;
            /**
             * Plays the audio file once with no handle (fire-and-forget).
             * @param path Path to an audio file (.wav / .ogg / .mp3).
             */
            playOneShot(path: string): void;
            /**
             * Immediately stops the voice associated with the given handle.
             * @param handle Handle returned by a previous play() call.
             */
            stop(handle: AudioHandle): void;
        };

        // ---------------------------------------------------------------------------
        // Scene — scene and actor management
        // ---------------------------------------------------------------------------
        /** Proxy object representing an Actor found via the Scene API. */
        declare interface ActorProxy {
            name: string;
            tag: string;
            active: boolean;
            transform: { x: number; y: number };
            destroy(): void;
        }

        declare const Scene: {
            /**
             * Finds the first actor in the active scene with the given name.
             * @param name Actor name to search for.
             * @returns An actor proxy, or null if not found.
             */
            find(name: string): ActorProxy | null;
            /**
             * Finds all actors in the active scene that share the given tag.
             * @param tag Tag to search for.
             * @returns An array of actor proxies (may be empty).
             */
            findByTag(tag: string): ActorProxy[];
            /**
             * Creates and adds a new actor to the scene, optionally initialised
             * from a prefab descriptor file.
             * @param prefab Path to a prefab file, or a name hint.
             * @param x     Initial world X position.
             * @param y     Initial world Y position.
             * @returns A proxy for the newly created actor.
             */
            instantiate(prefab: string, x: number, y: number): ActorProxy;
            /**
             * Requests a scene transition. The new scene is loaded at the end of
             * the current frame.
             * @param scene Path or name of the scene to load.
             */
            load(scene: string): void;
        };

        // ---------------------------------------------------------------------------
        // Debug — logging utilities
        // ---------------------------------------------------------------------------
        declare const Debug: {
            /**
             * Writes an informational message to the engine log and stdout.
             * Accepts any number of arguments; they are joined with spaces.
             */
            log(...args: any[]): void;
            /**
             * Writes a warning message to the engine log and stdout.
             * Accepts any number of arguments; they are joined with spaces.
             */
            warn(...args: any[]): void;
            /**
             * Writes an error message to the engine log and stdout.
             * Accepts any number of arguments; they are joined with spaces.
             */
            error(...args: any[]): void;
        };

        // ---------------------------------------------------------------------------
        // Vector2 — 2D vector math utilities
        // ---------------------------------------------------------------------------
        /** Plain {x, y} value object used throughout the Vector2 API. */
        declare interface Vec2 {
            x: number;
            y: number;
        }

        declare const Vector2: {
            /**
             * Creates a new {x, y} vector object.
             * @param x Horizontal component.
             * @param y Vertical component.
             */
            create(x: number, y: number): Vec2;
            /**
             * Returns the component-wise sum of two vectors.
             */
            add(a: Vec2, b: Vec2): Vec2;
            /**
             * Returns the component-wise difference (a − b).
             */
            sub(a: Vec2, b: Vec2): Vec2;
            /**
             * Returns the vector scaled by a scalar.
             * @param v Input vector.
             * @param s Scalar multiplier.
             */
            scale(v: Vec2, s: number): Vec2;
            /**
             * Returns the unit vector in the same direction as v.
             * Returns {x:0, y:0} if v has zero length.
             */
            normalize(v: Vec2): Vec2;
            /**
             * Returns the dot product of two vectors.
             */
            dot(a: Vec2, b: Vec2): number;
            /**
             * Returns the Euclidean distance between two points.
             */
            distance(a: Vec2, b: Vec2): number;
            /**
             * Returns the length (magnitude) of a vector.
             */
            length(v: Vec2): number;
        };

        // ---------------------------------------------------------------------------
        // Lifecycle function stubs — define these in your script as needed
        // ---------------------------------------------------------------------------

        /** Called once when the script component is first attached to an actor. */
        declare function onAwake(): void;

        /** Called once on the first frame after the scene has started. */
        declare function onStart(): void;

        /**
         * Called every frame during the variable-rate update.
         * @param dt Elapsed time in seconds since the last frame.
         */
        declare function onUpdate(dt: number): void;

        /**
         * Called at a fixed rate (default 60 Hz) regardless of frame rate.
         * Use this for physics-dependent logic.
         * @param dt Fixed timestep in seconds (Engine.Config.FixedTimestep).
         */
        declare function onFixedUpdate(dt: number): void;

        /**
         * Called every frame after all Update() calls have completed.
         * Use this for camera follow or anything that must react to moved objects.
         * @param dt Elapsed time in seconds since the last frame.
         */
        declare function onLateUpdate(dt: number): void;

        /** Called just before the actor is destroyed or the scene unloads. */
        declare function onDestroy(): void;

        /**
         * Called when this actor's collider first contacts another collider.
         * @param data Collision contact data including the other actor and surface info.
         */
        declare function onCollisionEnter(data: {
            other: ActorProxy;
            contactPoint: Vec2;
            normal: Vec2;
            relativeVelocity: number;
        }): void;

        /**
         * Called when another actor's collider enters this actor's trigger volume.
         * @param other Proxy for the actor that entered the trigger.
         */
        declare function onTriggerEnter(other: ActorProxy): void;
        """;
}
