using System.Diagnostics;

namespace SexyBiscuit.Engine.Scripting;

/// <summary>
/// Generates a TypeScript declaration file (<c>.d.ts</c>) that describes the
/// entire SexyBiscuit script API exposed by <see cref="ScriptBridge"/>.
///
/// Drop the generated file into your scripts workspace and point VS Code at it
/// via a <c>jsconfig.json</c> or <c>tsconfig.json</c> <c>typeRoots</c> entry
/// to get full IntelliSense, hover types, and parameter hints with zero build steps.
///
/// Usage:
/// <code>
///   // At engine startup (editor mode):
///   TypeScriptDefinitions.WriteToFile("Scripts/sb-engine.d.ts");
/// </code>
/// </summary>
public static class TypeScriptDefinitions
{
    // =========================================================================
    // Public API
    // =========================================================================

    /// <summary>
    /// Returns the complete <c>.d.ts</c> content as a string.
    /// The declarations cover every global and lifecycle function exposed by
    /// <see cref="ScriptBridge"/> and <see cref="ScriptComponent"/>.
    /// </summary>
    public static string Generate() => DtsContent;

    /// <summary>
    /// Writes the <c>.d.ts</c> content to <paramref name="outputPath"/>,
    /// creating any intermediate directories as needed.
    /// Overwrites any existing file at that path.
    /// </summary>
    /// <param name="outputPath">
    /// Destination file path, e.g. <c>"Scripts/sb-engine.d.ts"</c>.
    /// </param>
    public static void WriteToFile(string outputPath)
    {
        if (string.IsNullOrWhiteSpace(outputPath))
            throw new ArgumentException("outputPath must not be empty.", nameof(outputPath));

        try
        {
            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(outputPath, DtsContent, System.Text.Encoding.UTF8);
            System.Diagnostics.Debug.WriteLine($"[TypeScriptDefinitions] Written to: {outputPath}");
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"[TypeScriptDefinitions] Failed to write '{outputPath}': {ex.Message}");
            throw;
        }
    }

    // =========================================================================
    // Declaration content
    // =========================================================================

    // Stored as a verbatim string constant so there is no runtime I/O or
    // reflection cost.  Update this whenever ScriptBridge changes.
    private const string DtsContent =
        """
        // =============================================================================
        // SexyBiscuit Engine — Script API Declarations
        // Auto-generated by TypeScriptDefinitions.cs — do not hand-edit.
        // Place this file in your Scripts/ folder and reference it from jsconfig.json.
        //
        // This surface is shared with the HTML5 runtime: a script that uses only what is
        // declared here runs unchanged under both engines. The contract is pinned by
        // html5/src/scripting/bridge-api.json.
        // =============================================================================

        /** Plain {x, y} value object used throughout the API. */
        declare interface Vec2 {
            x: number;
            y: number;
        }

        /** Opaque handle returned by Audio.play(). Pass it to Audio.stop() to halt playback. */
        declare interface AudioHandle {
            readonly id: number;
        }

        /**
         * A component reached through getComponent(). Every schema-declared property is
         * readable and writable under its C# name and its camelCase name ("GravityScale" or
         * "gravityScale"); vectors read as {x, y} and colours as "#RRGGBBAA".
         */
        declare interface ComponentProxy {
            readonly type: string;
            readonly actor: ActorProxy;
            enabled: boolean;
            [property: string]: any;
        }

        /** A ScriptComponent seen from another script. */
        declare interface ScriptProxy extends ComponentProxy {
            /** Calls a top-level function the other script defines and returns its result. */
            invoke(name: string, ...args: any[]): any;
            /** The same as invoke(). */
            call(name: string, ...args: any[]): any;
        }

        /** Proxy object representing an Actor found via the Scene API or a collision. */
        declare interface ActorProxy {
            readonly id: number;
            name: string;
            tag: string;
            active: boolean;
            transform: { x: number; y: number; rotation: number };
            getComponent(type: string): ComponentProxy | null;
            destroy(): void;
        }

        /** The actor's Transform3D, when it has one. Rotations are Euler angles in degrees. */
        declare interface Transform3DProxy {
            x: number;
            y: number;
            z: number;
            rotX: number;
            rotY: number;
            rotZ: number;
            lookAt(x: number, y: number, z: number): void;
        }

        // ---------------------------------------------------------------------------
        // actor — the Actor that owns this script component
        // ---------------------------------------------------------------------------
        declare const actor: {
            /** Stable numeric id, unique within the running scene. */
            readonly id: number;
            /** Display name of the actor (editable). */
            name: string;
            /** Tag string used for collision filtering and scene queries. */
            tag: string;
            /** Whether this actor is active and updated each frame. */
            active: boolean;
            /** The same object as the `transform` global. */
            readonly transform: typeof transform;
            /** The actor's Transform3D, or null in a 2D scene. */
            readonly transform3d: Transform3DProxy | null;
            /** The first component of the named type, or null. */
            getComponent(type: string): ComponentProxy | null;
            /** Adds a component by type name and returns its proxy. */
            addComponent(type: string): ComponentProxy | null;
            /** Remove this actor from the scene at the end of the current frame. */
            destroy(): void;
        };

        // ---------------------------------------------------------------------------
        // transform — the actor's Transform component
        // ---------------------------------------------------------------------------
        declare const transform: {
            /** World-space X position. */
            x: number;
            /** World-space Y position. */
            y: number;
            /** World-space rotation in radians. */
            rotation: number;
            /** World-space horizontal scale. */
            scaleX: number;
            /** World-space vertical scale. */
            scaleY: number;
            /** Rotates the actor so it faces the point (x, y) in world space. */
            lookAt(x: number, y: number): void;
            /** The distance from this transform to another {x, y}. */
            distanceTo(other: { x: number; y: number }): number;
        };

        /** The actor's Transform3D, or null in a 2D scene. */
        declare const transform3d: Transform3DProxy | null;

        // ---------------------------------------------------------------------------
        // Input — input query API
        // ---------------------------------------------------------------------------
        declare const Input: {
            /** True on the frame the named action becomes active. */
            isPressed(action: string): boolean;
            /** True while the named action is active. */
            isHeld(action: string): boolean;
            /** True on the frame the named action stops being active. */
            isReleased(action: string): boolean;
            /** The axis value for the named action, -1..1. */
            getAxis(action: string): number;
            /** Mouse cursor X in screen pixels. */
            readonly mouseX: number;
            /** Mouse cursor Y in screen pixels. */
            readonly mouseY: number;
            /** Mouse movement since the last frame. */
            readonly mouseDeltaX: number;
            readonly mouseDeltaY: number;
            /** Scroll wheel movement since the last frame, in notches. */
            readonly scrollDelta: number;
            /** Keys by name: "A", "a", "KeyA", "Space", "ArrowLeft" and "Left" all work. */
            isKeyDown(key: string): boolean;
            isKeyHeld(key: string): boolean;
            isKeyPressed(key: string): boolean;
            isKeyReleased(key: string): boolean;
            /** Mouse buttons: 0 left, 1 middle, 2 right, or "Left" / "Middle" / "Right". */
            isMouseDown(button: number | string): boolean;
            isMouseHeld(button: number | string): boolean;
            isMousePressed(button: number | string): boolean;
            isMouseReleased(button: number | string): boolean;
            /** Active touches. */
            readonly touchCount: number;
            getTouch(index: number): { id: number; x: number; y: number; phase: string } | null;
            /** The left on-screen joystick, -1..1 on each axis. */
            readonly joystickX: number;
            readonly joystickY: number;
        };

        // ---------------------------------------------------------------------------
        // Audio — audio playback API
        // ---------------------------------------------------------------------------
        declare const Audio: {
            /** Starts playback and returns a handle; id is 0 when nothing could play. */
            play(path: string, loop?: boolean): AudioHandle;
            /** Plays the file once, fire-and-forget. */
            playOneShot(path: string, volume?: number): void;
            /** Stops the voice behind a handle (or a raw id). */
            stop(handle: AudioHandle | number): void;
            /** Sets the master volume, 0..1. */
            setVolume(volume: number): void;
        };

        // ---------------------------------------------------------------------------
        // Scene — scene and actor management
        // ---------------------------------------------------------------------------
        declare const Scene: {
            /** The name of the scene this actor is in. */
            readonly name: string;
            /** The first actor with the given name, or null. */
            find(name: string): ActorProxy | null;
            /** Every actor with the given name. */
            findAll(name: string): ActorProxy[];
            /** Every actor with the given tag. An empty array is still truthy. */
            findByTag(tag: string): ActorProxy[];
            /** The first actor with the given tag, or null. */
            findFirstByTag(tag: string): ActorProxy | null;
            /** Creates an empty actor in this scene at (x, y). */
            createActor(name: string, x?: number, y?: number): ActorProxy;
            /** Adds a component to an actor by type name, applying {Property: value} pairs. */
            addComponent(actor: ActorProxy, type: string, properties?: Record<string, any>): ComponentProxy | null;
            /** Removes an actor at the end of the frame. */
            destroy(actor: ActorProxy): void;
            /** The same as destroy(). */
            destroyActor(actor: ActorProxy): void;
            /** Instantiates a prefab file at (x, y), or an empty actor named after the path. */
            instantiate(prefab: string, x?: number, y?: number): ActorProxy;
            /** Requests a scene transition at the end of the frame. */
            load(scene: string): void;
        };

        // ---------------------------------------------------------------------------
        // Physics — 2D world queries
        // ---------------------------------------------------------------------------
        declare const Physics: {
            /** The closest hit along a ray, or null. */
            raycast(originX: number, originY: number, dirX: number, dirY: number, maxDistance?: number):
                { actor: ActorProxy; x: number; y: number; normalX: number; normalY: number; distance: number } | null;
            /** Every actor whose collider overlaps the circle. */
            overlapCircle(x: number, y: number, radius: number): ActorProxy[];
            /** Every actor whose collider overlaps the axis-aligned box. */
            overlapBox(x: number, y: number, width: number, height: number): ActorProxy[];
        };

        // ---------------------------------------------------------------------------
        // Time — frame timing
        // ---------------------------------------------------------------------------
        declare const Time: {
            readonly deltaTime: number;
            readonly unscaledDeltaTime: number;
            /** Scaled seconds since the engine started. */
            readonly time: number;
            readonly frameCount: number;
            readonly fps: number;
            /** 0 pauses gameplay, 0.5 is slow motion, 2 is double speed. */
            timeScale: number;
        };

        // ---------------------------------------------------------------------------
        // Network — present so a multiplayer script runs solo; no transport is attached
        // ---------------------------------------------------------------------------
        declare const Network: {
            readonly localId: number;
            readonly isServer: boolean;
            readonly isConnected: boolean;
            isLocalPlayer(id: number): boolean;
            startServer(port?: number): boolean;
            connect(address?: string): boolean;
            sendToAll(type: string, data?: any): void;
            broadcast(type: string, data?: any): void;
        };

        // ---------------------------------------------------------------------------
        // Debug — logging utilities
        // ---------------------------------------------------------------------------
        declare const Debug: {
            /** Writes an informational message. Arguments are joined with spaces. */
            log(...args: any[]): void;
            /** Writes a warning. */
            warn(...args: any[]): void;
            /** Writes an error. */
            error(...args: any[]): void;
        };

        /** The same as Debug.log / Debug.warn / Debug.error. */
        declare function log(...args: any[]): void;
        declare function warn(...args: any[]): void;
        declare function error(...args: any[]): void;

        // ---------------------------------------------------------------------------
        // Vector2 — 2D vector math over plain {x, y} objects
        // ---------------------------------------------------------------------------
        declare const Vector2: {
            create(x: number, y: number): Vec2;
            add(a: Vec2, b: Vec2): Vec2;
            /** a - b */
            sub(a: Vec2, b: Vec2): Vec2;
            scale(v: Vec2, s: number): Vec2;
            /** The unit vector, or {x: 0, y: 0} for a zero vector. */
            normalize(v: Vec2): Vec2;
            dot(a: Vec2, b: Vec2): number;
            distance(a: Vec2, b: Vec2): number;
            length(v: Vec2): number;
        };

        // ---------------------------------------------------------------------------
        // Collisions
        // ---------------------------------------------------------------------------
        /** Contact data handed to the collision hooks. tag and name forward to `other`. */
        declare interface CollisionData {
            other: ActorProxy;
            contactPoint: Vec2;
            normal: Vec2;
            relativeVelocity: number;
            readonly tag: string;
            readonly name: string;
        }

        // ---------------------------------------------------------------------------
        // Chibi — MakeChibi's characters
        // ---------------------------------------------------------------------------

        /**
         * Spawning, dressing and animating a chibi character.
         *
         * These are namespace functions rather than members of the actor you get back,
         * because a script-created actor proxy has no attachTo of its own.
         */
        declare namespace Chibi {
            /**
             * Spawns a character from a `.chibi` recipe under Assets/.
             *
             * The recipe is read from disk, so the body appears a frame or two later;
             * the actor itself is usable at once.
             */
            function spawn(recipePath: string, x?: number, y?: number, z?: number): ActorProxy | null;

            /** A coordinated random character. The same seed is always the same character. */
            function random(seed: number, x?: number, y?: number, z?: number): ActorProxy | null;

            /**
             * Plays a clip, cross-fading over `blend` seconds.
             * Locomotion: "idle", "walk", "run". Keyed: "wave", "hit", "jump", "cheer",
             * "sit", "die". False for a name that is neither.
             */
            function play(chibi: ActorProxy, clip: string, blend?: number): boolean;

            /** Stops whatever is playing, returning the character to rest. */
            function stop(chibi: ActorProxy): void;

            /** Repaints one colour slot: skin, hair, eyes, top, bottom, shoes, accent. */
            function setColour(chibi: ActorProxy, slot: string, hex: string): boolean;

            /** Swaps one style slot — head, hair, eyes, body, legs, feet — and rebuilds. */
            function setStyle(chibi: ActorProxy, slot: string, variant: string): boolean;

            /** Hangs an actor off a socket: Head, Face, Hand_L, Hand_R, Back. */
            function attach(chibi: ActorProxy, socket: string, actor: ActorProxy): boolean;

            /** The socket's own actor, for reading where it is. Null for an unknown name. */
            function socket(chibi: ActorProxy, socket: string): ActorProxy | null;
        }

        // ---------------------------------------------------------------------------
        // Lifecycle function stubs — define these in your script as needed
        // ---------------------------------------------------------------------------

        /** Called once when the script loads, after the actor has joined its scene. */
        declare function onAwake(): void;

        /** Called once on the first frame after the scene has started. */
        declare function onStart(): void;

        /** Called every frame. @param dt Seconds since the last frame. */
        declare function onUpdate(dt: number): void;

        /** Called at a fixed rate regardless of frame rate. Use for physics-dependent logic. */
        declare function onFixedUpdate(dt: number): void;

        /** Called every frame after every onUpdate has run. */
        declare function onLateUpdate(dt: number): void;

        /** Called just before the actor is destroyed or the scene unloads. */
        declare function onDestroy(): void;

        /** Called when this actor's collider first contacts another collider. */
        declare function onCollisionEnter(data: CollisionData): void;
        /** Called every physics step while the contact persists. */
        declare function onCollisionStay(data: CollisionData): void;
        /** Called when the contact ends. */
        declare function onCollisionExit(data: CollisionData): void;

        /** Called when another collider enters this actor's trigger volume. */
        declare function onTriggerEnter(other: ActorProxy): void;
        /** Called every physics step while it stays inside. */
        declare function onTriggerStay(other: ActorProxy): void;
        /** Called when it leaves. */
        declare function onTriggerExit(other: ActorProxy): void;
        """;
}
